import { useState } from 'react';

export default function Home() {
  const [workout, setWorkout] = useState('');
    const [duration, setDuration] = useState('');
      const [result, setResult] = useState('');
        const [loading, setLoading] = useState(false);
          const [history, setHistory] = useState([]);

            const handleSubmit = async (e) => {
                e.preventDefault();
                    setLoading(true);
                        setResult('');
                            try {
                                  const response = await fetch('/api/calories', {
                                          method: 'POST',
                                                  headers: { 'Content-Type': 'application/json' },
                                                          body: JSON.stringify({ workout, duration }),
                                                                });
                                                                      const data = await response.json();
                                                                            setResult(data.calories);
                                                                                  setHistory((prev) => [
                                                                                          { workout, duration, calories: data.calories },
                                                                                                  ...prev,
                                                                                                        ]);
                                                                                                              setWorkout('');
                                                                                                                    setDuration('');
                                                                                                                        } catch (err) {
                                                                                                                              setResult('Error calculating calories. Please try again.');
                                                                                                                                  }
                                                                                                                                      setLoading(false);
                                                                                                                                        };
                                                                                                                                        
                                                                                                                                          return (
                                                                                                                                              <div style={{ maxWidth: 600, margin: '40px auto', fontFamily: 'Arial, sans-serif', padding: '0 20px' }}>
                                                                                                                                                    <h1 style={{ color: '#2563eb' }}>AI Fitness Tracker</h1>
                                                                                                                                                          <p style={{ color: '#555' }}>Tell me your workout and I will calculate how many calories you burned using AI!</p>
                                                                                                                                                                
                                                                                                                                                                      <form onSubmit={handleSubmit} style={{ background: '#f3f4f6', padding: 24, borderRadius: 12 }}>
                                                                                                                                                                              <div style={{ marginBottom: 16 }}>
                                                                                                                                                                                        <label style={{ display: 'block', marginBottom: 6, fontWeight: 'bold' }}>
                                                                                                                                                                                                    What workout did you do?
                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                value={workout}
                                                                                                                                                                                                                                                            onChange={(e) => setWorkout(e.target.value)}
                                                                                                                                                                                                                                                                        placeholder="e.g. Running, cycling, push-ups..."
                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                style={{ width: '100%', padding: 10, borderRadius: 8, border: '1px solid #d1d5db', fontSize: 16, boxSizing: 'border-box' }}
                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                          <div style={{ marginBottom: 16 }}>
                                                                                                                                                                                                                                                                                                                                    <label style={{ display: 'block', marginBottom: 6, fontWeight: 'bold' }}>
                                                                                                                                                                                                                                                                                                                                                For how long? (minutes)
                                                                                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                                                                                                            value={duration}
                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setDuration(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="e.g. 30"
                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                            min="1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ width: '100%', padding: 10, borderRadius: 8, border: '1px solid #d1d5db', fontSize: 16, boxSizing: 'border-box' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ background: '#2563eb', color: 'white', border: 'none', padding: '12px 24px', borderRadius: 8, fontSize: 16, cursor: 'pointer', width: '100%' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? 'Calculating...' : 'Calculate Calories Burned'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginTop: 24, padding: 20, background: '#dcfce7', borderRadius: 12, border: '1px solid #86efac' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 style={{ margin: 0, color: '#16a34a' }}>Result:</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ margin: '8px 0 0', fontSize: 16 }}>{result}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {history.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginTop: 32 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>Workout History</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {history.map((item, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={i} style={{ background: '#f9fafb', padding: 16, borderRadius: 8, marginBottom: 12, border: '1px solid #e5e7eb' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>{item.workout}</strong> - {item.duration} minutes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ margin: '4px 0 0', color: '#555', fontSize: 14 }}>{item.calories}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
